# -*- coding: utf-8 -*-
"""Env app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QSmJOABTtcszk6CYcQo2Ce_FhzHEd852
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from fpdf import FPDF
import random

# Load dataset
df = pd.read_csv("sebi_compliance_audit_data.csv")

st.set_page_config(page_title="SEBI Compliance Dashboard", layout="wide")
st.title("📜 SEBI Regulation 30 Compliance Audit Dashboard")

# Company selector
entity = st.selectbox("Select Company or Startup:", df["Entity"].tolist())
record = df[df["Entity"] == entity].squeeze()

# Display main metrics
st.subheader(f"🧾 Compliance Summary for {entity}")
st.metric("Compliance Level", record["SEBI_Compliance_Level"])
st.metric("Penalty", record["Penalty"])
st.metric("Disclosure Delay", record["Disclosure_Delay"])

# Display detailed info
st.write("### Regulatory Disclosure Details")
st.write(f"- **Type:** {record['Type']}")
st.write(f"- **Regulatory Action:** {record['Regulatory_Action']}")
st.write(f"- **Material Disclosures Made:** {record['Material_Disclosures_Made']}")
st.write(f"- **Last Disclosure Date:** {record['Last_Disclosure_Date']}")

# Simulated materiality check
st.write("### 🧠 Simulated Materiality Threshold Check")
simulated_event_value = random.randint(10, 500)  # in Crores
company_net_worth = random.randint(1000, 5000)  # in Crores
threshold = 10  # 10% of net worth assumed material
materiality_percent = round((simulated_event_value / company_net_worth) * 100, 2)

st.write(f"- **Simulated Event Value:** ₹{simulated_event_value} Cr")
st.write(f"- **Estimated Company Net Worth:** ₹{company_net_worth} Cr")
st.write(f"- **Materiality Threshold:** {threshold}%")
st.write(f"- **Calculated Impact:** {materiality_percent}%")

if materiality_percent >= threshold:
    st.warning("🚨 This event likely requires material disclosure to SEBI.")
else:
    st.success("✅ Disclosure not mandatory based on simulated threshold.")

# Pie chart visualization
st.write("### Disclosure Status Breakdown")
labels = ["Disclosures Made", "Undisclosed"]
made = record["Material_Disclosures_Made"]
undisclosed = 10 - made if made < 10 else 0
fig, ax = plt.subplots()
ax.pie([made, undisclosed], labels=labels, autopct="%1.1f%%", colors=["#4CAF50", "#FF5722"])
ax.axis("equal")
st.pyplot(fig)

# Bar chart of late disclosure summary
st.write("### 📊 Company-wide Late Disclosure Summary")
summary = df.groupby(["Type", "Disclosure_Delay"]).size().unstack(fill_value=0)
summary["Total"] = summary.sum(axis=1)
summary["% Delayed"] = round((summary["Delayed"] / summary["Total"] * 100), 2)

fig2, ax2 = plt.subplots()
summary[["Delayed", "On Time"]] = summary[["Delayed", "No Delay"]] if "No Delay" in summary.columns else summary[["Delayed"]]
summary[["On Time"]] = summary[["On Time"]].fillna(0)
summary[["Delayed", "On Time"]].plot(kind="bar", stacked=True, color=["#F44336", "#4CAF50"], ax=ax2)
ax2.set_title("Late vs On-Time Disclosures by Company Type")
ax2.set_ylabel("Number of Companies")
ax2.legend(title="Disclosure Status")
st.pyplot(fig2)

# PDF Export Button
if st.button("📄 Export Compliance Report to PDF"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=14)
    pdf.cell(200, 10, txt="SEBI Compliance Report", ln=True, align="C")
    pdf.set_font("Arial", size=12)
    pdf.ln(10)
    pdf.cell(200, 10, txt=f"Entity: {entity}", ln=True)
    pdf.cell(200, 10, txt=f"Type: {record['Type']}", ln=True)
    pdf.cell(200, 10, txt=f"Compliance Level: {record['SEBI_Compliance_Level']}", ln=True)
    pdf.cell(200, 10, txt=f"Penalty: {record['Penalty']}", ln=True)
    pdf.cell(200, 10, txt=f"Disclosure Delay: {record['Disclosure_Delay']}", ln=True)
    pdf.cell(200, 10, txt=f"Regulatory Action: {record['Regulatory_Action']}", ln=True)
    pdf.cell(200, 10, txt=f"Disclosures Made: {record['Material_Disclosures_Made']}", ln=True)
    pdf.cell(200, 10, txt=f"Last Disclosure Date: {record['Last_Disclosure_Date']}", ln=True)
    pdf.cell(200, 10, txt=f"Simulated Event Value: ₹{simulated_event_value} Cr", ln=True)
    pdf.cell(200, 10, txt=f"Net Worth: ₹{company_net_worth} Cr", ln=True)
    pdf.cell(200, 10, txt=f"Impact: {materiality_percent}%", ln=True)
    pdf.cell(200, 10, txt=f"Material Disclosure Required: {'Yes' if materiality_percent >= threshold else 'No'}", ln=True)

    filename = f"SEBI_Compliance_Report_{entity.replace(' ', '_')}.pdf"
    pdf.output(filename)

    with open(filename, "rb") as f:
        st.download_button("📥 Download SEBI PDF Report", f, file_name=filename)

# Dataset download button
st.download_button(
    label="📥 Download Full SEBI Dataset",
    data=df.to_csv(index=False),
    file_name="sebi_compliance_audit_data.csv",
    mime="text/csv"
)